[package]
name = "ragout"
version = "0.31.32"
edition = "2021"
description = "Terminal raw mode utilities"
license = "MIT"
repository = "https://github.com/uraneko/ragout"
readme = "README.md"
keywords = ["terminal", "raw_mode", "cli"]
categories = ["command-line-interface"]
exclude = ["resources/logs/", "Cargo.lock"]
documentation = "https://docs.rs/ragout"

[dependencies]
crossterm = "0.27.0"
ragout_custom_events_macro = { version = "0.1.0", optional = true }
ragout_assistant = "0.1.0"

[[example]]
name = "basic"
path = "examples/basic.rs"

[features]
default = ["lib", "styled"]
lib = []
styled = []
custom_events = ["dep:ragout_custom_events_macro"]
# the debug_logs feature would be enabled only when the debug_logs feature in ragout_assistant is enabled
debug_logs = ["ragout_assistant/debug_logs"]
